#ttps://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: nextjs
    app.kubernetes.io/name: nextjs
    app.kubernetes.io/part-of: fullstack-website
  name: nextjs-config
  data:
  NEXT_PUBLIC_BACKEND_URL: localhost
  NEXT_PUBLIC_BACKEND_PORT: 3001
  NEXT_PUBLIC_FRONTEND_VERSION: 0.0.1
