# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: nestjs
    app.kubernetes.io/name: nestjs
    app.kubernetes.io/part-of: professional-website
  name: nestjs-config
data:

  # DATABASE_HOST: 10.96.73.175
  # DATABASE_PORT: '5433'
  # DATABASE_USER: postgres
  # DATABASE_PASSWORD: root
  # DATABASE_NAME: postgres
  MODE: development
  # BASE_PORT: '3000'
  # JWT_SECRET: test

  # BASE_HOST=127.0.0.1

# kubectl get po -o wide  (there has to be a better way)
