apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres
# make sure namespace exists

resources:
- namespace.yaml

helmCharts:
- name: ingress-nginx
  version: 4.4.2
  repo: https://kubernetes.github.io/ingress-nginx
  valuesFile: values.yaml
  namespace: nginx
  # releaseName: 
