apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres
# make sure namespace exists

resources:
- namespace.yaml
# - postgres-ingress.yaml

helmCharts:
- name: postgresql
  version: 12.1.6
  repo: https://charts.bitnami.com/bitnami
  valuesFile: values.yaml
  namespace: postgres
  releaseName: db
